<?php
/**
 * TL_ROOT/system/modules/menu/languages/fr/tl_menu.php 
 * 
 * Contao extension: menu 1.0.2 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : LGPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_menu']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_menu']['title']['1'] = "Veuillez, s'il vous plaît, entrer le titre du plat.";
$GLOBALS['TL_LANG']['tl_menu']['tstamp']['0'] = "Date de révision";
$GLOBALS['TL_LANG']['tl_menu']['tstamp']['1'] = "Date et heure de la dernière révision.";
$GLOBALS['TL_LANG']['tl_menu']['title_legend'] = "Titre";
$GLOBALS['TL_LANG']['tl_menu']['new']['0'] = "Nouveau plat";
$GLOBALS['TL_LANG']['tl_menu']['new']['1'] = "Créer un nouveau plat";
$GLOBALS['TL_LANG']['tl_menu']['show']['0'] = "Détails du plat";
$GLOBALS['TL_LANG']['tl_menu']['show']['1'] = "Afficher les détails du plat ID %s";
$GLOBALS['TL_LANG']['tl_menu']['edit']['0'] = "Éditer le plat";
$GLOBALS['TL_LANG']['tl_menu']['edit']['1'] = "Éditer le plat ID %s";
$GLOBALS['TL_LANG']['tl_menu']['copy']['0'] = "Dupliquer le plat";
$GLOBALS['TL_LANG']['tl_menu']['copy']['1'] = "Dupliquer le plat ID %s";
$GLOBALS['TL_LANG']['tl_menu']['delete']['0'] = "Supprimer le plat";
$GLOBALS['TL_LANG']['tl_menu']['delete']['1'] = "Supprimer le plat ID %s";
 
?>
