<?php
/**
 * TL_ROOT/system/modules/menu/languages/fr/tl_module.php 
 * 
 * Contao extension: menu 1.0.2 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : LGPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['menu_collection']['0'] = "Ensemble de menus";
$GLOBALS['TL_LANG']['tl_module']['menu_collection']['1'] = "Veuillez, s'il vous plaît, sélectionner l'ensemble de menus que vous désirez afficher.";
$GLOBALS['TL_LANG']['tl_module']['next_weeks']['0'] = "Prochain ensemble de menus";
$GLOBALS['TL_LANG']['tl_module']['next_weeks']['1'] = "Veuillez, s'il vous plaît, entrer le nombre de semaines pendant lesquelles les prochains menus doivent être affichés.";
$GLOBALS['TL_LANG']['tl_module']['prev_weeks']['0'] = "Précédent ensemble de menus";
$GLOBALS['TL_LANG']['tl_module']['prev_weeks']['1'] = "Veuillez, s'il vous plaît, entrer le nombre de semaines pendant lesquelles les menus précédents doivent être affichés.";
$GLOBALS['TL_LANG']['tl_module']['menu_template']['0'] = "Modèles du menu";
$GLOBALS['TL_LANG']['tl_module']['menu_template']['1'] = "Veuillez, s'il vous plaît, choisir un modèle pour le menu.";
 
?>
