<?php
/**
 * TL_ROOT/system/modules/menu/languages/fr/tl_menu_week.php 
 * 
 * Contao extension: menu 1.0.2 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : LGPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_menu_week']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_menu_week']['title']['1'] = "Veuillez, s'il vous plaît, entrer le titre du menu de la semaine.";
$GLOBALS['TL_LANG']['tl_menu_week']['alias']['0'] = "Alias du menu de la semaine";
$GLOBALS['TL_LANG']['tl_menu_week']['alias']['1'] = "L'alias est une référence unique pour le menu qui peut être appelé à la place de son ID.";
$GLOBALS['TL_LANG']['tl_menu_week']['tstamp']['0'] = "Date de révision";
$GLOBALS['TL_LANG']['tl_menu_week']['tstamp']['1'] = "Date et heure de la dernière révision.";
$GLOBALS['TL_LANG']['tl_menu_week']['monday']['0'] = "Date du lundi de la semaine";
$GLOBALS['TL_LANG']['tl_menu_week']['monday']['1'] = "Date du lundi commençant le menu de la semaine.";
$GLOBALS['TL_LANG']['tl_menu_week']['has_alternate_text']['0'] = "Utiliser un texte alternatif";
$GLOBALS['TL_LANG']['tl_menu_week']['has_alternate_text']['1'] = "Cochez si vous voulez utiliser un texte alternatif à la place du plat et du prix.";
$GLOBALS['TL_LANG']['tl_menu_week']['alternate_text']['0'] = "Texte alternatif";
$GLOBALS['TL_LANG']['tl_menu_week']['alternate_text']['1'] = "Le texte alternatif sera utilisé à la place du plat et du prix, par exemple « Fermé le lundi ».";
$GLOBALS['TL_LANG']['tl_menu_week']['has_additional_text']['0'] = "Ajouter un texte supplémentaire";
$GLOBALS['TL_LANG']['tl_menu_week']['has_additional_text']['1'] = "Cocher si vous voulez ajouter un texte supplémentaire en-dessous du titre du plat";
$GLOBALS['TL_LANG']['tl_menu_week']['additional_text']['0'] = "Texte supplémentaire";
$GLOBALS['TL_LANG']['tl_menu_week']['additional_text']['1'] = "Texte supplémentaire utilisé avec le titre du plat (par ex.: \"fermé au public à partir de 18 heures»)";
$GLOBALS['TL_LANG']['tl_menu_week']['add_new_menu']['0'] = "Ajouter un nouveau plat";
$GLOBALS['TL_LANG']['tl_menu_week']['add_new_menu']['1'] = "Cochez si vous souhaitez ajouter un nouveau plat dans la base de données au lieu de choisir un plat existant.";
$GLOBALS['TL_LANG']['tl_menu_week']['new_menu']['0'] = "Nouveau plat";
$GLOBALS['TL_LANG']['tl_menu_week']['new_menu']['1'] = "Nom du nouveau plat.";
$GLOBALS['TL_LANG']['tl_menu_week']['menu']['0'] = "Plat";
$GLOBALS['TL_LANG']['tl_menu_week']['menu']['1'] = "Sélectionnez un plat dans la liste des plats disponibles.";
$GLOBALS['TL_LANG']['tl_menu_week']['suffix']['0'] = "Annexe";
$GLOBALS['TL_LANG']['tl_menu_week']['suffix']['1'] = "Ajouter une annexe pour la journée, par exemple, \"Lundi de Pâques\"";
$GLOBALS['TL_LANG']['tl_menu_week']['price']['0'] = "Prix";
$GLOBALS['TL_LANG']['tl_menu_week']['price']['1'] = "Insérez un prix pour le plat.";
$GLOBALS['TL_LANG']['tl_menu_week']['menu_week_legend'] = "Titre du menu de la semaine.";
$GLOBALS['TL_LANG']['tl_menu_week']['monday_legend'] = "Lundi";
$GLOBALS['TL_LANG']['tl_menu_week']['tuesday_legend'] = "Mardi";
$GLOBALS['TL_LANG']['tl_menu_week']['wednesday_legend'] = "Mercredi";
$GLOBALS['TL_LANG']['tl_menu_week']['thursday_legend'] = "Jeudi";
$GLOBALS['TL_LANG']['tl_menu_week']['friday_legend'] = "Vendredi";
$GLOBALS['TL_LANG']['tl_menu_week']['saturday_legend'] = "Samedi";
$GLOBALS['TL_LANG']['tl_menu_week']['sunday_legend'] = "Dimanche";
$GLOBALS['TL_LANG']['tl_menu_week']['new']['0'] = "Nouveau menu de la semaine";
$GLOBALS['TL_LANG']['tl_menu_week']['new']['1'] = "Créer un nouveau menu de la semaine";
$GLOBALS['TL_LANG']['tl_menu_week']['show']['0'] = "Détails du menu de la semaine";
$GLOBALS['TL_LANG']['tl_menu_week']['show']['1'] = "Afficher les détails du menu de la semaine ID %s";
$GLOBALS['TL_LANG']['tl_menu_week']['edit']['0'] = "Éditer le menu de la semaine";
$GLOBALS['TL_LANG']['tl_menu_week']['edit']['1'] = "Éditer le menu de la semaine ID %s";
$GLOBALS['TL_LANG']['tl_menu_week']['copy']['0'] = "Dupliquer le menu de la semaine";
$GLOBALS['TL_LANG']['tl_menu_week']['copy']['1'] = "Dupliquer le menu de la semaine ID %s";
$GLOBALS['TL_LANG']['tl_menu_week']['delete']['0'] = "Supprimer le menu de la semaine";
$GLOBALS['TL_LANG']['tl_menu_week']['delete']['1'] = "Supprimer le menu de la semaine ID %s";
$GLOBALS['TL_LANG']['tl_menu_week']['export']['0'] = "Exporter le menu de la semaine";
$GLOBALS['TL_LANG']['tl_menu_week']['export']['1'] = "Exporter le menu de la semaine ID %s";
$GLOBALS['TL_LANG']['tl_menu_week']['title_default'] = "Calendrier du menu de la semaine {{W}}, {{Y}}";
$GLOBALS['TL_LANG']['tl_menu_week']['price_format'] = "€%s";
$GLOBALS['TL_LANG']['tl_menu_week']['price_error'] = "Le champ %s doit être un prix valide.";
$GLOBALS['TL_LANG']['tl_menu_week']['date_format_day'] = "{{l}}, {{m}}-{{d}}";
$GLOBALS['TL_LANG']['tl_menu_week']['export_to_pdf'] = "Exporter au format PDF";
 
?>
