<?php
/**
 * TL_ROOT/system/modules/menu/languages/fr/tl_menus.php 
 * 
 * Contao extension: menu 1.0.2 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : LGPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_menus']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_menus']['title']['1'] = "Veuillez, s'il vous plaît, entrer un titre pour l'ensemble des menus.";
$GLOBALS['TL_LANG']['tl_menus']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_menus']['alias']['1'] = "L'alias est une référence unique pour l'ensemble des menus qui peut être appelé à la place de son ID.";
$GLOBALS['TL_LANG']['tl_menus']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_menus']['description']['1'] = "Veuillez, s'il vous plaît, entrer une courte description sur l'ensemble des menus.";
$GLOBALS['TL_LANG']['tl_menus']['tstamp']['0'] = "Date de révision";
$GLOBALS['TL_LANG']['tl_menus']['tstamp']['1'] = "Date et heure de la dernière révision.";
$GLOBALS['TL_LANG']['tl_menus']['title_legend'] = "Titre";
$GLOBALS['TL_LANG']['tl_menus']['new']['0'] = "Nouvel ensemble de menus";
$GLOBALS['TL_LANG']['tl_menus']['new']['1'] = "Créer un nouvel ensemble de menus";
$GLOBALS['TL_LANG']['tl_menus']['show']['0'] = "Détails de l'ensemble de menus";
$GLOBALS['TL_LANG']['tl_menus']['show']['1'] = "Afficher les détails de l'ensemble de menus ID %s";
$GLOBALS['TL_LANG']['tl_menus']['edit']['0'] = "Éditer l'ensemble de menus";
$GLOBALS['TL_LANG']['tl_menus']['edit']['1'] = "Éditer l'ensemble de menus ID %s";
$GLOBALS['TL_LANG']['tl_menus']['copy']['0'] = "Dupliquer l'ensemble de menus";
$GLOBALS['TL_LANG']['tl_menus']['copy']['1'] = "Dupliquer l'ensemble de menus ID %s";
$GLOBALS['TL_LANG']['tl_menus']['delete']['0'] = "Supprimer l'ensemble de menus";
$GLOBALS['TL_LANG']['tl_menus']['delete']['1'] = "Supprimer l'ensemble de menus ID %s";
 
?>
